package main.java.stashed;

// Generated Dec 1, 2011 6:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Creditaccount generated by hbm2java
 */
public class CreditAccount implements java.io.Serializable {

	private long pkaccountid;
	private Long purchasedby;
	private Long purchaseddate;
	private Double spendcredit;
	private Double availablecredit;
	private Integer uc;
	private Date dc;
	private Integer um;
	private Date dm;
	private Double availableinternationalcredit;
	private Double spendinternationalcredit;
	private Set<ClientManager> clientmanagers = new HashSet<ClientManager>(0);

	public CreditAccount() {
	}

	public CreditAccount(long pkaccountid) {
		this.pkaccountid = pkaccountid;
	}

	public CreditAccount(long pkaccountid, Long purchasedby,
                         Long purchaseddate, Double spendcredit, Double availablecredit,
                         Integer uc, Date dc, Integer um, Date dm,
                         Double availableinternationalcredit,
                         Double spendinternationalcredit, Set<ClientManager> clientmanagers) {
		this.pkaccountid = pkaccountid;
		this.purchasedby = purchasedby;
		this.purchaseddate = purchaseddate;
		this.spendcredit = spendcredit;
		this.availablecredit = availablecredit;
		this.uc = uc;
		this.dc = dc;
		this.um = um;
		this.dm = dm;
		this.availableinternationalcredit = availableinternationalcredit;
		this.spendinternationalcredit = spendinternationalcredit;
		this.clientmanagers = clientmanagers;
	}

	public long getPkaccountid() {
		return this.pkaccountid;
	}

	public void setPkaccountid(long pkaccountid) {
		this.pkaccountid = pkaccountid;
	}

	public Long getPurchasedby() {
		return this.purchasedby;
	}

	public void setPurchasedby(Long purchasedby) {
		this.purchasedby = purchasedby;
	}

	public Long getPurchaseddate() {
		return this.purchaseddate;
	}

	public void setPurchaseddate(Long purchaseddate) {
		this.purchaseddate = purchaseddate;
	}

	public Double getSpendcredit() {
		return this.spendcredit;
	}

	public void setSpendcredit(Double spendcredit) {
		this.spendcredit = spendcredit;
	}

	public Double getAvailablecredit() {
		return this.availablecredit;
	}

	public void setAvailablecredit(Double availablecredit) {
		this.availablecredit = availablecredit;
	}

	public Integer getUc() {
		return this.uc;
	}

	public void setUc(Integer uc) {
		this.uc = uc;
	}

	public Date getDc() {
		return this.dc;
	}

	public void setDc(Date dc) {
		this.dc = dc;
	}

	public Integer getUm() {
		return this.um;
	}

	public void setUm(Integer um) {
		this.um = um;
	}

	public Date getDm() {
		return this.dm;
	}

	public void setDm(Date dm) {
		this.dm = dm;
	}

	public Double getAvailableinternationalcredit() {
		return this.availableinternationalcredit;
	}

	public void setAvailableinternationalcredit(
			Double availableinternationalcredit) {
		this.availableinternationalcredit = availableinternationalcredit;
	}

	public Double getSpendinternationalcredit() {
		return this.spendinternationalcredit;
	}

	public void setSpendinternationalcredit(Double spendinternationalcredit) {
		this.spendinternationalcredit = spendinternationalcredit;
	}

	public Set<ClientManager> getClientmanagers() {
		return this.clientmanagers;
	}

	public void setClientmanagers(Set<ClientManager> clientmanagers) {
		this.clientmanagers = clientmanagers;
	}

}
