package main.java.stashed;

// Generated Dec 1, 2011 6:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Credits generated by hbm2java
 */
public class Credits implements java.io.Serializable {

	private long pkcreditid;
	private ClientManager clientmanager;
	private Long purchasedby;
	private Double purchasedamount;
	private Date purchaseddate;
	private Double purchasedinternationalamount;

	public Credits() {
	}

	public Credits(long pkcreditid) {
		this.pkcreditid = pkcreditid;
	}

	public Credits(long pkcreditid, ClientManager clientmanager,
			Long purchasedby, Double purchasedamount, Date purchaseddate,
			Double purchasedinternationalamount) {
		this.pkcreditid = pkcreditid;
		this.clientmanager = clientmanager;
		this.purchasedby = purchasedby;
		this.purchasedamount = purchasedamount;
		this.purchaseddate = purchaseddate;
		this.purchasedinternationalamount = purchasedinternationalamount;
	}

	public long getPkcreditid() {
		return this.pkcreditid;
	}

	public void setPkcreditid(long pkcreditid) {
		this.pkcreditid = pkcreditid;
	}

	public ClientManager getClientmanager() {
		return this.clientmanager;
	}

	public void setClientmanager(ClientManager clientmanager) {
		this.clientmanager = clientmanager;
	}

	public Long getPurchasedby() {
		return this.purchasedby;
	}

	public void setPurchasedby(Long purchasedby) {
		this.purchasedby = purchasedby;
	}

	public Double getPurchasedamount() {
		return this.purchasedamount;
	}

	public void setPurchasedamount(Double purchasedamount) {
		this.purchasedamount = purchasedamount;
	}

	public Date getPurchaseddate() {
		return this.purchaseddate;
	}

	public void setPurchaseddate(Date purchaseddate) {
		this.purchaseddate = purchaseddate;
	}

	public Double getPurchasedinternationalamount() {
		return this.purchasedinternationalamount;
	}

	public void setPurchasedinternationalamount(
			Double purchasedinternationalamount) {
		this.purchasedinternationalamount = purchasedinternationalamount;
	}

}
