package main.java.stashed;

// Generated Dec 1, 2011 6:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private long pkroleid;
	private String rolename;
	private Set<SysUser> sysusers = new HashSet<SysUser>(0);

	public Role() {
	}

	public Role(long pkroleid) {
		this.pkroleid = pkroleid;
	}

	public Role(long pkroleid, String rolename, Set<SysUser> sysusers) {
		this.pkroleid = pkroleid;
		this.rolename = rolename;
		this.sysusers = sysusers;
	}

	public long getPkroleid() {
		return this.pkroleid;
	}

	public void setPkroleid(long pkroleid) {
		this.pkroleid = pkroleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public Set<SysUser> getSysusers() {
		return this.sysusers;
	}

	public void setSysusers(Set<SysUser> sysusers) {
		this.sysusers = sysusers;
	}

}
