package main.java.stashed;

// Generated Dec 1, 2011 6:05:27 PM by Hibernate Tools 3.4.0.CR1

import com.ecomm.pl4sms.persistence.entities.SendingInterface;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Smscproxyproperty generated by hbm2java
 */
public class SMSCProxyProperty implements java.io.Serializable {

	private long pksmscpropid;
	private SMSCProxy smscproxy;
	private String replypath;
	private String sourcenumber;
	private Boolean concatination;
	private String offeredinterface;
	private Boolean deliveryreciepts;
	// speed of sms per sec
	private String speedofsms;
	private Double smscost;
	private Double replycost;
	private String discount;
	private String kannelsmscname;
	private boolean alphanumericadd;
	public boolean isAlphanumericadd() {
		return alphanumericadd;
	}

	public void setAlphanumericadd(boolean alphanumericadd) {
		this.alphanumericadd = alphanumericadd;
	}

	private Long uc;
	private Date dc;
	private Long um;
	private Date dm;
	private Long ud;
	private Date dd;
	private Long sendinginterfaceid;
	
	private String name;
	private Set<SendingInterface> sendinginterfaces = new HashSet<SendingInterface>(
			0);

	public SMSCProxyProperty() {
	}

	public SMSCProxyProperty(long pksmscpropid) {
		this.pksmscpropid = pksmscpropid;
	}

	public SMSCProxyProperty(long pksmscpropid, SMSCProxy smscproxy,
                             String replypath, String sourcenumber, Boolean concatination,
                             String offeredinterface, Boolean deliveryreciepts,
                             String speedofsms, Double smscost, Double replycost,
                             String discount, String kannelsmscname, Long uc, Date dc, Long um,
                             Date dm, Long ud, Date dd, Long sendinginterfaceid, String name,
                             Set<SendingInterface> sendinginterfaces) {
		this.pksmscpropid = pksmscpropid;
		this.smscproxy = smscproxy;
		this.replypath = replypath;
		this.sourcenumber = sourcenumber;
		this.concatination = concatination;
		this.offeredinterface = offeredinterface;
		this.deliveryreciepts = deliveryreciepts;
		this.speedofsms = speedofsms;
		this.smscost = smscost;
		this.replycost = replycost;
		this.discount = discount;
		this.kannelsmscname = kannelsmscname;
		this.uc = uc;
		this.dc = dc;
		this.um = um;
		this.dm = dm;
		this.ud = ud;
		this.dd = dd;
		this.sendinginterfaceid = sendinginterfaceid;
		
		this.name = name;
		this.sendinginterfaces = sendinginterfaces;
	}

	public long getPksmscpropid() {
		return this.pksmscpropid;
	}

	public void setPksmscpropid(long pksmscpropid) {
		this.pksmscpropid = pksmscpropid;
	}

	public SMSCProxy getSmscproxy() {
		return this.smscproxy;
	}

	public void setSmscproxy(SMSCProxy smscproxy) {
		this.smscproxy = smscproxy;
	}

	public String getReplypath() {
		return this.replypath;
	}

	public void setReplypath(String replypath) {
		this.replypath = replypath;
	}

	public String getSourcenumber() {
		return this.sourcenumber;
	}

	public void setSourcenumber(String sourcenumber) {
		this.sourcenumber = sourcenumber;
	}

	public Boolean getConcatination() {
		return this.concatination;
	}

	public void setConcatination(Boolean concatination) {
		this.concatination = concatination;
	}

	public String getOfferedinterface() {
		return this.offeredinterface;
	}

	public void setOfferedinterface(String offeredinterface) {
		this.offeredinterface = offeredinterface;
	}

	public Boolean getDeliveryreciepts() {
		return this.deliveryreciepts;
	}

	public void setDeliveryreciepts(Boolean deliveryreciepts) {
		this.deliveryreciepts = deliveryreciepts;
	}

	public String getSpeedofsms() {
		return this.speedofsms;
	}

	public void setSpeedofsms(String speedofsms) {
		this.speedofsms = speedofsms;
	}

	public Double getSmscost() {
		return this.smscost;
	}

	public void setSmscost(Double smscost) {
		this.smscost = smscost;
	}

	public Double getReplycost() {
		return this.replycost;
	}

	public void setReplycost(Double replycost) {
		this.replycost = replycost;
	}

	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	public String getKannelsmscname() {
		return this.kannelsmscname;
	}

	public void setKannelsmscname(String kannelsmscname) {
		this.kannelsmscname = kannelsmscname;
	}

	public Long getUc() {
		return this.uc;
	}

	public void setUc(Long uc) {
		this.uc = uc;
	}

	public Date getDc() {
		return this.dc;
	}

	public void setDc(Date dc) {
		this.dc = dc;
	}

	public Long getUm() {
		return this.um;
	}

	public void setUm(Long um) {
		this.um = um;
	}

	public Date getDm() {
		return this.dm;
	}

	public void setDm(Date dm) {
		this.dm = dm;
	}

	public Long getUd() {
		return this.ud;
	}

	public void setUd(Long ud) {
		this.ud = ud;
	}

	public Date getDd() {
		return this.dd;
	}

	public void setDd(Date dd) {
		this.dd = dd;
	}

	public Long getSendinginterfaceid() {
		return this.sendinginterfaceid;
	}

	public void setSendinginterfaceid(Long sendinginterfaceid) {
		this.sendinginterfaceid = sendinginterfaceid;
	}

	

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<SendingInterface> getSendinginterfaces() {
		return this.sendinginterfaces;
	}

	public void setSendinginterfaces(Set<SendingInterface> sendinginterfaces) {
		this.sendinginterfaces = sendinginterfaces;
	}

}
