package main.java.stashed;

// Generated Jan 2, 2012 6:59:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Smsobj generated by hbm2java
 */
public class SMSObj implements java.io.Serializable {

	private long pksmsobjid;
	private String smsid;
	private String smsc;
	private String reciever;
	private String sender;
	private String message;
	private String footer;
	private String operator;
	private Date loadeddate;
	private Date futuredate;
	private Long sysuserid;
	private Long clientmanager;
	private Integer smscount;
	private Long holdingaccountid;
	private String deliverinfo;
	private String status;
	
	public SMSObj() {
	}

	public SMSObj(long pksmsobjid) {
		this.pksmsobjid = pksmsobjid;
	}

	public SMSObj(long pksmsobjid, String smsid, String smsc, String reciever,
                  String sender, String message, String footer, String operator,
                  Date loadeddate, Date futuredate, Long sysuserid,
                  Long clientmanager, Integer smscount, Long holdingaccountid,
                  String deliverinfo, String status) {
		this.pksmsobjid = pksmsobjid;
		this.smsid = smsid;
		this.smsc = smsc;
		this.reciever = reciever;
		this.sender = sender;
		this.message = message;
		this.footer = footer;
		this.operator = operator;
		this.loadeddate = loadeddate;
		this.futuredate = futuredate;
		this.sysuserid = sysuserid;
		this.clientmanager = clientmanager;
		this.smscount = smscount;
		this.holdingaccountid = holdingaccountid;
		this.deliverinfo = deliverinfo;
		this.status = status;
	}

	public long getPksmsobjid() {
		return this.pksmsobjid;
	}

	public void setPksmsobjid(long pksmsobjid) {
		this.pksmsobjid = pksmsobjid;
	}

	public String getSmsid() {
		return this.smsid;
	}

	public void setSmsid(String smsid) {
		this.smsid = smsid;
	}

	public String getSmsc() {
		return this.smsc;
	}

	public void setSmsc(String smsc) {
		this.smsc = smsc;
	}

	public String getReciever() {
		return this.reciever;
	}

	public void setReciever(String reciever) {
		this.reciever = reciever;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getFooter() {
		return this.footer;
	}

	public void setFooter(String footer) {
		this.footer = footer;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Date getLoadeddate() {
		return this.loadeddate;
	}

	public void setLoadeddate(Date loadeddate) {
		this.loadeddate = loadeddate;
	}

	public Date getFuturedate() {
		return this.futuredate;
	}

	public void setFuturedate(Date futuredate) {
		this.futuredate = futuredate;
	}

	public Long getSysuserid() {
		return this.sysuserid;
	}

	public void setSysuserid(Long sysuserid) {
		this.sysuserid = sysuserid;
	}

	public Long getClientmanager() {
		return this.clientmanager;
	}

	public void setClientmanager(Long clientmanager) {
		this.clientmanager = clientmanager;
	}

	public Integer getSmscount() {
		return this.smscount;
	}

	public void setSmscount(Integer smscount) {
		this.smscount = smscount;
	}

	public Long getHoldingaccountid() {
		return this.holdingaccountid;
	}

	public void setHoldingaccountid(Long holdingaccountid) {
		this.holdingaccountid = holdingaccountid;
	}

	public String getDeliverinfo() {
		return this.deliverinfo;
	}

	public void setDeliverinfo(String deliverinfo) {
		this.deliverinfo = deliverinfo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
