package main.java.stashed;

// Generated Dec 1, 2011 6:05:27 PM by Hibernate Tools 3.4.0.CR1

import com.ecomm.pl4sms.persistence.entities.MobileNetworkOperator;

import java.util.Date;

/**
 * Startnumber generated by hbm2java
 */
public class StartNumber implements java.io.Serializable {

	private long pkstartnumberid;
	private MobileNetworkOperator mno;
	private String number;
	private Long uc;
	private Date dc;
	private Long um;
	private Date dm;
	private Long ud;
	private Date dd;

	public StartNumber() {
	}

	public StartNumber(long pkstartnumberid) {
		this.pkstartnumberid = pkstartnumberid;
	}

	public StartNumber(long pkstartnumberid, MobileNetworkOperator mno, String number, Long uc,
                       Date dc, Long um, Date dm, Long ud, Date dd) {
		this.pkstartnumberid = pkstartnumberid;
		this.mno = mno;
		this.number = number;
		this.uc = uc;
		this.dc = dc;
		this.um = um;
		this.dm = dm;
		this.ud = ud;
		this.dd = dd;
	}

	public long getPkstartnumberid() {
		return this.pkstartnumberid;
	}

	public void setPkstartnumberid(long pkstartnumberid) {
		this.pkstartnumberid = pkstartnumberid;
	}

	public MobileNetworkOperator getMno() {
		return this.mno;
	}

	public void setMno(MobileNetworkOperator mno) {
		this.mno = mno;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Long getUc() {
		return this.uc;
	}

	public void setUc(Long uc) {
		this.uc = uc;
	}

	public Date getDc() {
		return this.dc;
	}

	public void setDc(Date dc) {
		this.dc = dc;
	}

	public Long getUm() {
		return this.um;
	}

	public void setUm(Long um) {
		this.um = um;
	}

	public Date getDm() {
		return this.dm;
	}

	public void setDm(Date dm) {
		this.dm = dm;
	}

	public Long getUd() {
		return this.ud;
	}

	public void setUd(Long ud) {
		this.ud = ud;
	}

	public Date getDd() {
		return this.dd;
	}

	public void setDd(Date dd) {
		this.dd = dd;
	}

}
