package main.java.stashed;

// Generated Dec 1, 2011 6:05:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sysuser generated by hbm2java
 */
public class SysUser implements java.io.Serializable {

	private long pkuserid;
	private Role role;
	private String username;
	private String userid;
	private String password;
	private String clientref;
	private Integer uc;
	private Date dc;
	private Integer um;
	private Date dm;
	
	private Set<ClientManager> clientmanagers = new HashSet<ClientManager>(0);

	public SysUser() {
	}

	public SysUser(long pkuserid) {
		this.pkuserid = pkuserid;
	}

	public SysUser(long pkuserid, Role role, String username, String userid,
                   String password, String clientref, Integer uc, Date dc, Integer um,
                   Date dm, Set<ClientManager> clientmanagers) {
		this.pkuserid = pkuserid;
		this.role = role;
		this.username = username;
		this.userid = userid;
		this.password = password;
		this.clientref = clientref;
		this.uc = uc;
		this.dc = dc;
		this.um = um;
		this.dm = dm;
		this.clientmanagers = clientmanagers;
	}

	public long getPkuserid() {
		return this.pkuserid;
	}

	public void setPkuserid(long pkuserid) {
		this.pkuserid = pkuserid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getClientref() {
		return this.clientref;
	}

	public void setClientref(String clientref) {
		this.clientref = clientref;
	}

	public Integer getUc() {
		return this.uc;
	}

	public void setUc(Integer uc) {
		this.uc = uc;
	}

	public Date getDc() {
		return this.dc;
	}

	public void setDc(Date dc) {
		this.dc = dc;
	}

	public Integer getUm() {
		return this.um;
	}

	public void setUm(Integer um) {
		this.um = um;
	}

	public Date getDm() {
		return this.dm;
	}

	public void setDm(Date dm) {
		this.dm = dm;
	}

	public Set<ClientManager> getClientmanagers() {
		return this.clientmanagers;
	}

	public void setClientmanagers(Set<ClientManager> clientmanagers) {
		this.clientmanagers = clientmanagers;
	}

}
